### ISSUE TITLE
Missing FarmerArFragment causes app to crash on boot

### ISSUE THREAD

**Issue by vidia** [SmartAsApps/HerdingLlamas#1]
Hi, 

I was taking a look at this project to get some more experience with SceneForm, but I ran into an issue trying to run what you have. 

It looks like there is a fragment missing from this repo. Specifically de.smartasapps.urbanllamafarmer.FarmerArFragment. Without it the app builds just fine because it seems because the fragment is only referenced in the Layout files, and therefore it is never checked at build time. 

Was there a file missing in your commit? 

Thanks!

**Comment by vidia** [comment]
It looks like I can replace that reference with a generic ArFragment and get some functionality. But I am not completely sure if I am missing some functionality that is supposed to be there.

**Comment by StevenMohr** [comment]
Thanks for spotting this! I've made the changes locally but hadn't pushed it yet. Now everything is up-to-date and should work as expected
